name: Approve Resource and Create PR

on:
  issue_comment:
    types: [created]

jobs:
  process-approval:
    # Only run when:
    # 1. Comment is on an issue (not a PR)
    # 2. Issue has resource-submission and validation-passed labels
    # 3. Comment contains /approve command
    # 4. Commenter has write permissions (maintainer/owner)
    if: |
      github.event.issue.pull_request == null &&
      contains(github.event.issue.labels.*.name, 'resource-submission') &&
      contains(github.event.issue.labels.*.name, 'validation-passed') &&
      contains(github.event.comment.body, '/approve') &&
      (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'COLLABORATOR')
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests PyGithub
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: React to approval comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });
      
      - name: Parse issue and create PR
        id: create_pr
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # First parse the issue to get resource data
          python scripts/parse_issue_form.py > resource_data.json
          
          # Create the PR with the resource
          python scripts/create_resource_pr.py \
            --issue-number $ISSUE_NUMBER \
            --resource-data resource_data.json \
            > pr_result.json
          
          # Extract PR URL for next step
          PR_URL=$(jq -r '.pr_url' pr_result.json)
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          
          # Extract branch name for cleanup if needed
          BRANCH_NAME=$(jq -r '.branch_name' pr_result.json)
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      
      - name: Comment on issue with results
        uses: actions/github-script@v7
        with:
          script: |
            const pr_url = '${{ steps.create_pr.outputs.pr_url }}';
            const issue_number = context.issue.number;
            
            let comment_body = '## ✅ Resource Approved!\n\n';
            
            if (pr_url && pr_url !== 'null') {
              comment_body += `🎉 A pull request has been created with your resource: ${pr_url}\n\n`;
              comment_body += 'The PR will be merged shortly, and you\'ll be notified when your resource is live.\n\n';
              comment_body += 'Thank you for contributing to Awesome Claude Code!';
              
              // Add approved label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: ['approved', 'pr-created']
              });
              
              // Close the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                state: 'closed',
                state_reason: 'completed'
              });
            } else {
              comment_body += '❌ There was an error creating the pull request.\n\n';
              comment_body += 'Please check the workflow logs for details.';
              
              // Add error label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: ['error-creating-pr']
              });
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment_body
            });
      
      - name: Handle rejection command
        if: contains(github.event.comment.body, '/reject')
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const issue_number = context.issue.number;
            
            // Extract rejection reason
            const reasonMatch = comment.match(/\/reject\s+(.*)/);
            const reason = reasonMatch ? reasonMatch[1] : 'No reason provided';
            
            // React to comment
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: '-1'
            });
            
            // Add rejection comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `## ❌ Submission Rejected\n\n**Reason:** ${reason}\n\nYou may create a new submission if you'd like to try again.`
            });
            
            // Update labels and close
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['rejected']
            });
            
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              state: 'closed',
              state_reason: 'not_planned'
            });
      
      - name: Handle request changes command
        if: contains(github.event.comment.body, '/request-changes')
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const issue_number = context.issue.number;
            
            // Extract requested changes
            const changesMatch = comment.match(/\/request-changes\s+(.*)/s);
            const changes = changesMatch ? changesMatch[1] : 'Please review the submission requirements.';
            
            // React to comment
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });
            
            // Add comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `## 🔄 Changes Requested\n\n${changes}\n\nPlease edit your issue to address these points. The validation will run again automatically after you make changes.`
            });
            
            // Update labels
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['changes-requested']
            });